Repository aws/aws-lambda-go, pull requests merged in 2019-07, with the labels that each got.

#204 Bump testify to 1.3.0
  .travis.yml
  go.mod
  go.sum
Labels: stage/accepted

#212 Update S3 Event to working Go file
  events/README_S3.md
Labels: stage/accepted

#203 Linter pass
  cmd/build-lambda-zip/main.go
  events/attributevalue_test.go
  events/cloudwatch_logs.go
  events/cognito.go
  events/firehose_test.go
  lambda/handler.go
Labels: stage/accepted

#211 Extend events.SimpleEmailReceiptAction fields
  events/ses.go
  events/ses_test.go
  events/testdata/ses-lambda-event.json
  events/testdata/ses-s3-event.json
  events/testdata/ses-sns-event.json
Labels: enhancement, stage/in-progress

#208 Add Lambda handler wrapper for SNS-based custom resources
  cfn/wrap.go
Labels: enhancement, stage/more-info-needed
